In [ ]:
# read .parquet file
path = '/content/avalanche.blocks.43114_20250523_225817_9aac8c5624ee4c169290f2e72128fafc.parquet'

import pandas as pd
df = pd.read_parquet(path)
df.head()

,chainId,blockNumber,blockTimestamp,blockHash,txCount,baseFee,gasUsed,gasLimit,gasCost,parentHash,feesSpent,cumulativeTransactions
0,43114,62600796,1748041095,0xa2963728d2f09debce0ddedf799a0679927902d15951...,5,204058476,1270582,16000000,800000,0x27d7d245fbb50fae8692b8d4e3fa5f948043b9394813...,467032148533257,578848529

In [ ]:
# read .parquet file
path = '/content/avax.metrics_20250523_231657_a51caeb8894749a1935fbebd2d225ebe.parquet'

import pandas as pd
df = pd.read_parquet(path)
df.head()

# transform in a object
# Rename the variable to avoid conflict with the imported json module
json_string = df.to_json(orient='records')

# display with identation
import json
# Pass the json_string variable to json.loads
print(json.dumps(json.loads(json_string), indent=4, sort_keys=True))

[
    {
        "block": {
            "baseFee": "25000000000",
            "blockHash": "0x5b81be33dc24c1db90cf5d946ada17302cf4a03a1791ffbeb71eb6f1332ec773",
            "blockNumber": "15552355",
            "blockTimestamp": 1748042192,
            "chainId": "6119",
            "cumulativeTransactions": "23773593",
            "feesSpent": "1167399000000000",
            "gasCost": "0",
            "gasLimit": "60000000",
            "gasUsed": "43237",
            "parentHash": "0x6194d176bf44fafcb304140a90a55b055e15de29e706cc824ff01677db84e8a7",
            "txCount": 1
        }
    }
]

In [ ]:
# read .parquet file
path = '/content/avax.metrics_20250523_231657_a96c694bb7464469967aafb8180eff0b.parquet'

import pandas as pd
df = pd.read_parquet(path)
df.head()

# transform in a object
# Rename the variable to avoid conflict with the imported json module
json_string = df.to_json(orient='records')

# display with identation
import json
# Pass the json_string variable to json.loads
print(json.dumps(json.loads(json_string), indent=4, sort_keys=True))

[
    {
        "chain": {
            "chainId": "201",
            "chainLogoUri": "https://images.ctfassets.net/gcj8jwzm6086/62KzIedYATHGgRODAP5Py9/e290f4d8598ac8d30d80975a560cca8f/AvaCloud-512x512.png",
            "chainName": "monthly-gray-newt",
            "description": "",
            "enabledFeatures": [],
            "explorerUrl": "https://subnets-test.avax.network/monthlygra",
            "isTestnet": true,
            "networkToken": {
                "decimals": 18,
                "description": "",
                "logoUri": "https://images.ctfassets.net/gcj8jwzm6086/62KzIedYATHGgRODAP5Py9/e290f4d8598ac8d30d80975a560cca8f/AvaCloud-512x512.png",
                "name": "ZVV",
                "symbol": "ZVV"
            },
            "platformChainId": "2QqiyRpk1QRm4Na48JWqvA9pxXyhDi2wnMsxEKtX7Sf5cA1uoE",
            "private": false,
            "rpcUrl": "https://subnets.avax.network/monthlygra/testnet/rpc",
            "status": "OK",
            "subnetId": "2gHdmnHMvRWXz7rdrQVtcdTxDqM3KNAxgtq7srR5gBFjzUHP47",
            "vmId": "qCNtLHfuDPEosXo2UVDyzo2Chwf9ETu5f6ohNnmQMXuD2zmho",
            "vmName": "EVM",
            "wsUrl": ""
        }
    }
]

In [ ]:
# read .parquet file
path = '/content/avalanche.blockchains_20250524_023225_9d127392d5f44e2596315167f38d6ff6.parquet'

import pandas as pd
df = pd.read_parquet(path)
df.head()

,blockchainId,vmId,subnetId
0,2nsYq166yzgV5qvtM3vJQ6vKJTUXx8WLEg9HSJ7GfSx7xt...,srEXiWaHuhNyGwPUi444Tu47ZEDwxTWrbQiuD7FmgSAQ6X7Dy,qCccbQ4CJekniXpdgfdoFinEAkUf4wys9T89JNTK9CuvcMW81

In [ ]:
# read .parquet file
path = '/content/avax.metrics.activity_20250523_225906_11b747da96104f189e7e06965e221a4c.parquet'

import pandas as pd
df = pd.read_parquet(path)
df.head()

,activeAddresses,averageTxFee,averageTxPerBlock,chainId,failedTxCount,newAddressesCreated,period,successfulTxCount,timestamp,totalGasUsed,transactionCount
0,1250,0.00125,85.5,43114,150,145,30m0s,12350,1748041142,1250000000,12500